// Mocks generated by Mockito 5.4.6 from annotations
// in todolist_ai_native/test/voice_kanban_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todolist_ai_native/src/api/voice_kanban_api_client.dart' as _i3;
import 'package:todolist_ai_native/src/api/voice_kanban_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCreateEntryResponse_0 extends _i1.SmartFake
    implements _i2.CreateEntryResponse {
  _FakeCreateEntryResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VoiceKanbanApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceKanbanApiClient extends _i1.Mock
    implements _i3.VoiceKanbanApiClient {
  @override
  _i4.Future<List<_i2.ParsedDraft>> parse(String? rawText) =>
      (super.noSuchMethod(
            Invocation.method(#parse, [rawText]),
            returnValue: _i4.Future<List<_i2.ParsedDraft>>.value(
              <_i2.ParsedDraft>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.ParsedDraft>>.value(
              <_i2.ParsedDraft>[],
            ),
          )
          as _i4.Future<List<_i2.ParsedDraft>>);

  @override
  _i4.Future<_i2.CreateEntryResponse> createEntry(String? rawText) =>
      (super.noSuchMethod(
            Invocation.method(#createEntry, [rawText]),
            returnValue: _i4.Future<_i2.CreateEntryResponse>.value(
              _FakeCreateEntryResponse_0(
                this,
                Invocation.method(#createEntry, [rawText]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.CreateEntryResponse>.value(
                  _FakeCreateEntryResponse_0(
                    this,
                    Invocation.method(#createEntry, [rawText]),
                  ),
                ),
          )
          as _i4.Future<_i2.CreateEntryResponse>);

  @override
  _i4.Future<List<_i2.ParsedItem>> listItems({_i2.ParsedItemType? type}) =>
      (super.noSuchMethod(
            Invocation.method(#listItems, [], {#type: type}),
            returnValue: _i4.Future<List<_i2.ParsedItem>>.value(
              <_i2.ParsedItem>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.ParsedItem>>.value(
              <_i2.ParsedItem>[],
            ),
          )
          as _i4.Future<List<_i2.ParsedItem>>);
}
